# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_trip_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
    ]
